### PR TITLE
Add IntrospectionProcessor

### PR DESCRIPTION
**Pull request by reececomo**
Added this to HE Web a few months ago and performance impact was negligible, should be fine for everything else.

* Adds "file", "class", "function" and "line" to logs, which are fantastic for filtering.

Apologies if I've messed up - I did this via GitHub web interface

### CODE REVIEW

**Review by jradtilbrook — CHANGES_REQUESTED** [review]
This will use this logger for everything above debug won't it? I don't think that should be the case. Perhaps make it configurable or at least a flag to enable/disable it

**Comment by reececomo** [comment]
> **I don't think that should be the case.**

I'd love to understand why

I want this on by default on everything we log. Most modern language loggers include this by default - Monolog was a bit late to the party.

**Edit:** It's >= DEBUG (so includes everything)

**Review by joshkulesza — APPROVED** [review]
Seems okay
apparently i disagree with jarryd on this

**Comment by jradtilbrook** [comment]
I have a few concerns:

1. This likely adds significant overhead to the logging output. Supporting infrastructure like metrics/monitoring pipelines of current users might not be ready to accept the additional data into that pipeline (I'm not even sure we are ready for it). Also, excessive logging has caused issues in the past (I can share more details privately if you would like).
2. This is open source. So we need to consider the side-effects for not just ourselves.
3. I don't believe the services we are using this in currently would benefit from this.

I see 2 options,

1. Make it disabled by default so users can upgrade if they wish to
2. Change the minimum logging level from DEBUG to something higher so that it decreases the load on the logging pipeline. It's quite possible that this is only helpful in warning or error cases since success path logging wouldn't benefit from knowing exact lines

**Comment by reececomo** [comment]
Fair point-of-view @jradtilbrook. I definitely am leaning more toward this should be standard on all repos (especially as open-source).

**Points for (IMHO):**
* It has far more day-to-day utility than nearly all of the other included processors.
* Application logs become more context-expressive, easier to filter and detailed, with virtually no overhead.
* All of our Laravel micro-services logger's would be on the same standard as HE Web - so the developer experience is more consistent.

I would love to get @nathanblogs hot take on this too.

**Review by SaxJ — APPROVED** [review]

**Review by tspencer244 — COMMENTED** [review]
I think we should be comparing xdebug traces to figure out the cost of these changes

**Comment by reececomo** [comment]
> I think we should be comparing xdebug traces to figure out the cost of these changes

We already implemented it on HE Web logging some time ago and the performance/memory hit was negligible.

It's fairly lightweight, and pretty industry-standard. I'm surprised we've waited this long to turn it on.

**Review by jradtilbrook — APPROVED** [review]

**Pull request merged**
